export const AUTH = {
  PAYLOAD_ALGORITHM: 'aes-192-cbc',
  PAYLOAD_PASSWORD: 'wtkwX1ywsnB',
  PAYLOAD_SALT: 'WV32JMr1kU',
  PAYLOAD_SALT_ROUND: 24,
  AUDIENCE_APP: 'project-basecode',
  PASSWORD_SALT_ROUND: 10,
};
